#!/bin/bash
url="https://pokeapi.co/api/v2/pokemon"
pokemons=(bulbasaur ivysaur venusaur charmander charmeleon)


if [ -d "./pokemon_data" ]; then
    echo "directory exists" > /dev/null
else
    mkdir pokemon_data
fi


for pokemon in ${pokemons[@]}; do
    echo "Fetching data for ${pokemon}"

    file="./pokemon_data/${pokemon}.json"
    
    p_url="${url}/${pokemon}"

    retry_count=3

    while [ $retry_count -gt 0 ]; do
        response=$(curl -s -w "%{http_code}" $p_url 2>> errors.log | jq .)
        
        status_code=$(echo "$response" | tail -n 1)
        
        if [[ $status_code -eq "200" ]]; then
            data=$(echo "$response" | head -n -1)

            echo $data | jq . > $file
            
            echo "Saved data to $file ✅"

            sleep 1
        
            break
        fi

        retry_count=$(( $retry_count - 1 ))
        
        sleep 1
    done    
done
