#!/bin/bash

url="https://pokeapi.co/api/v2/pokemon"

pokemons=(bulbasaur ivysaur venusaur charmander charmeleon)


if [ -d "./pokemon_data" ]; then
    echo "directory exists" > /dev/null
else
    mkdir pokemon_data
fi


for pokemon in ${pokemons[@]}; do
    echo "Fetching data for ${pokemon}"

    file="./pokemon_data/${pokemon}.json"
    
    p_url="${url}/${pokemon}"

    retry_count=3

    while [ $retry_count -gt 0 ]; do
        
        if [[ $retry_count -eq 1 ]]; then 
            echo "last retry attempt"
        fi


        retry_count=$(( $retry_count - 1 ))
    done

    #curl -s $p_url | jq . > ${file} 2>> error.log
    
    #echo "Saved data to $file ✅"
    
    #sleep 2
done
